# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7331c8e68f2ec5a1dbfc6e5337f436f384298109ed8a91d54edbcf8e308c4decb2570839cbe12cd2f77736918ad41bc2f9a0dcdf8e29d09f401bb1153c486de5

test:
  secret_key_base: 403941a3e4c3f2e82a6e6b48f260ecca3dd287d57b23f1d1b0635e43f2484e2b1a3972ff9a02a8ac849615d2e6d21e4d0e561e8740dcbfc1ec561866457363f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
